### ISSUE TITLE
Configuration with environment variables

### ISSUE THREAD

**Issue by forzagreen** [netsage-project/gdg#65]
It would be nice if we could specify environment variables in the configuration file `importer.yml`

This will enable us to isolate secrets (tokens and passwords), and safely commit the configuration file to version control.

**Comment by safaci2000** [comment]
That's mostly there.  I'll do a small patch though the nested level is a bit more of an issue.

You basically have to export the ENV values and run it so that it overrides the value.

Example:  CONTEXT_NAME="testing" gdg ctx show 

will override the value context_name from the config file.  You should be able to do that for any variable name.  
(This isn't quiet functional yet but just clarifying what will be supported)

https://github.com/spf13/viper is the library we're using.

**Comment by anders-ove** [comment]
I am trying to set environment variable for a token, but it does not seem to work.

I am setting it like this: GDG_CONTEXTS__MAIN__TOKEN="my-secret-token"

And this is my importer.yml file:

`context_name: main

contexts:
  main:
    output_path: backupdata
    url: https://my-grafana-instance/
    token: "get-from-repo-secrets"
    organization: Main Org
    ignore_filters: false # When set to true all Watched filtered folders will be ignored and ALL folders will be acted on
    watched:
      - General

global:
  debug: true
  ignore_ssl_errors: true ##when set to true will ignore invalid SSL errors`
  
Is there something wrong with my setup, or is this simply not working (yet)?

**Comment by forzagreen** [comment]
@anders-ove I think it's just not yet deployed. As of today the latest release is v0.1.8 (16 Nov 2021) https://github.com/netsage-project/gdg/releases

**Comment by anders-ove** [comment]
Thanks, @forzagreen. I also tried it on a copy of the master-branch (which has the PR in this issue included).

Also gave it a go to try to set the env variable through Go like this:
` os.Setenv("GDG_CONTEXTS__MAIN__TOKEN", "my-secret-token")`

But still no luck.

**Comment by safaci2000** [comment]
@anders-ove this isn't released yet, so you'll have to pull it via the hashID if you you use go get syntax.  I think this should work `go install github.com/netsage-project/gdg@7d9b620bce20f370c17660d292eab4d7241d161a`


I had a dumb mistake that somehow go passed code reviews as well.  I had it hard coded to the 'testing' context.  Try pulling the latest and let me know if it works as expected.

**Comment by muralikrishna8** [comment]
Hi,

Do you have any release date for this version?

**Comment by safaci2000** [comment]
Let me tag it and push it up.  I was asking you to confirm that it works for you.

**Comment by safaci2000** [comment]
It should be released now.

**Comment by muralikrishna8** [comment]
I had tested, and it worked for me. (pulling from the hashID)

Thanks.
