### ISSUE TITLE
Support instances with more than 1000 dashboards

### ISSUE THREAD

**Issue by cr1xu5** [netsage-project/gdg#68]
Thank you for this project!

When listing/importing dashboards from a Grafana instance with more than 1000 dashboards, you only get the dashboards within the watched folder that were returned in the first 1000 results. As result, in my case I only imported 37 dashboards instead of all 225.

I have no immediate need for this feature, but hopefully it could safe others some time or trouble in the short term.

**Comment by safaci2000** [comment]
Interesting. Good to know. I imagine pagination is required. I assume the default payload is 1000 after which the filtering occurs. I'll see if there's options to easily add that in.

**Comment by safaci2000** [comment]
A few optimizations to be looked at:
  - folderIds – List of folder id’s to search in for dashboards
  - limit – Limit the number of returned results (max 5000)
  - page – Use this parameter to access hits beyond limit. Numbering starts at 1. limit param acts as page size. Only available in Grafana v6.2+.


@cr1xu5 I can try to work around this, but I don't really have any Grafana instance that has over 5000 dashboards.  My testing will be a bit limited.

**Comment by safaci2000** [comment]
Fixed with PR #69

**Comment by cr1xu5** [comment]
Thank you @safaci2000 for your quick response and work! 5000 should be more than enough.
